import subprocess

import pytest


@pytest.fixture
def tone_m4a(tmp_path):
    """A 2-second 440 Hz tone in m4a, generated by ffmpeg."""
    path = tmp_path / "tone.m4a"
    subprocess.run(
        ["ffmpeg", "-v", "error", "-f", "lavfi", "-i",
         "sine=frequency=440:duration=2", "-c:a", "aac", str(path)],
        check=True,
    )
    return path
